INSERT INTO "STI".tratado (titulo,clasificacion,aprobado,firmaLugar,firmaFecha,numGaceta,fechaGaceta, canjeNotificacion,deposito,fechaDeposito,entradaVigor,duracion,periodo,volumen, pagina,observacion,contenido,status,usuarioT) VALUES ('NOTA REVERSAL CON EL PROGRAMA DE ASESORAMIENTO EN EL DESARROLLO URBANISTICO Y MEDIDAS ESTRUTURALES DE ASENTAMIENTO ENTRE EL REPRESENTANTE DE LA REPUBLICA DE VENEZUELA Y EL REPRESENTANTE DE LA REPUBLICA FEDERAL DE ALEMANIA.',FALSE,FALSE,'CARACAS','04/08/1987',NULL,NULL,NULL,TRUE,NULL,NULL,NULL,1987,30,381,NULL,NULL,2,'admin');
INSERT INTO "STI".pais VALUES (1,'ALEMANIA');
INSERT INTO "STI".grupo VALUES (1,'UE');
INSERT INTO "STI".tratado (titulo,clasificacion,aprobado,firmaLugar,firmaFecha,numGaceta,fechaGaceta, canjeNotificacion,deposito,fechaDeposito,entradaVigor,duracion,periodo,volumen, pagina,observacion,contenido,status,usuarioT) VALUES ('ACUERDO POR CANJE DE NOTAS SOBRE LA SUPRESION DE LOS VISADOS PARA TITULARES DE PASAPORTES DIPLOMATICOS.',FALSE,FALSE,'CARACAS','04/28/1989',NULL,NULL,NULL,TRUE,NULL,NULL,NULL,1989,32,131,NULL,NULL,2,'admin');
INSERT INTO "STI".pais VALUES (2,'ALEMANIA');
INSERT INTO "STI".grupo VALUES (2,'UE');
INSERT INTO "STI".tratado (titulo,clasificacion,aprobado,firmaLugar,firmaFecha,numGaceta,fechaGaceta, canjeNotificacion,deposito,fechaDeposito,entradaVigor,duracion,periodo,volumen, pagina,observacion,contenido,status,usuarioT) VALUES ('ACUERDO POR NOTAS DIPLOMATICAS SOBRE LA PROLONGACION DEL PROYECTO  FORTALECIMIENTO DE LOS SERVICIOS HIDROMETEOROLOGICOS NACIONALES .',FALSE,FALSE,'CARACAS','09/01/1993','35.317','10/14/1993',NULL,TRUE,NULL,'09/01/1993',NULL,1993,36,633,NULL,NULL,2,'admin');
INSERT INTO "STI".pais VALUES (3,'ALEMANIA');
INSERT INTO "STI".grupo VALUES (3,'UE');
INSERT INTO "STI".tratado (titulo,clasificacion,aprobado,firmaLugar,firmaFecha,numGaceta,fechaGaceta, canjeNotificacion,deposito,fechaDeposito,entradaVigor,duracion,periodo,volumen, pagina,observacion,contenido,status,usuarioT) VALUES ('ACUERDO POR NOTAS DIPLOMATICAS SOBRE EL PROYECTO  FOMENTO DE SERVICIO NACIONAL DE METROLOGIA (S.N.M.) .',FALSE,FALSE,'CARACAS','09/01/1993','35.317','10/14/1993',NULL,TRUE,NULL,'09/01/1993',NULL,1993,36,621,NULL,NULL,2,'admin');
INSERT INTO "STI".pais VALUES (4,'ALEMANIA');
INSERT INTO "STI".grupo VALUES (4,'UE');
INSERT INTO "STI".tratado (titulo,clasificacion,aprobado,firmaLugar,firmaFecha,numGaceta,fechaGaceta, canjeNotificacion,deposito,fechaDeposito,entradaVigor,duracion,periodo,volumen, pagina,observacion,contenido,status,usuarioT) VALUES ('ACUERDO SOBRE EL PROYECTO  ESCUELA DE ARTESANIA MADERERA EN LA COLONIA TOVAR .',FALSE,FALSE,'CARACAS','09/01/1991','35.317','10/14/1993',NULL,TRUE,NULL,'09/01/1993',NULL,1993,36,611,NULL,NULL,2,'admin');
INSERT INTO "STI".pais VALUES (5,'ALEMANIA');
INSERT INTO "STI".grupo VALUES (5,'UE');
INSERT INTO "STI".tratado (titulo,clasificacion,aprobado,firmaLugar,firmaFecha,numGaceta,fechaGaceta, canjeNotificacion,deposito,fechaDeposito,entradaVigor,duracion,periodo,volumen, pagina,observacion,contenido,status,usuarioT) VALUES ('CONVENIO BASICO SOBRE COOPERACION TECNICA.',FALSE,FALSE,'CARACAS','12/18/1991','4.477 EX','10/14/1992',NULL,TRUE,NULL,'11/20/1992',NULL,1992,35,295,NULL,NULL,2,'admin');
INSERT INTO "STI".pais VALUES (6,'ALEMANIA');
INSERT INTO "STI".grupo VALUES (6,'UE');
INSERT INTO "STI".tratado (titulo,clasificacion,aprobado,firmaLugar,firmaFecha,numGaceta,fechaGaceta, canjeNotificacion,deposito,fechaDeposito,entradaVigor,duracion,periodo,volumen, pagina,observacion,contenido,status,usuarioT) VALUES ('ACUERDO, POR CAMBIO DE NOTAS, PARA LA APLICACION A LA REPUBLICA FEDERAL  ALEMANA DE LAS DISPOSICIONES DE LA CONVENCION DE AVIACION CIVIL INTERNACIONAL Y DE LAS DEL CONVENIO RELATIVO AL TRANSITO DE LOS SERVICIOS AEREOS.',FALSE,FALSE,'CARACAS','02/06/1956',NULL,NULL,NULL,TRUE,NULL,NULL,NULL,1955,11,733,NULL,NULL,2,'admin');
INSERT INTO "STI".pais VALUES (7,'ALEMANIA');
INSERT INTO "STI".grupo VALUES (7,' ');